version: '2'
services:
  jenkins:
    # image: 'bitnami/jenkins:2'
    # image: dirane/jenkins-docker-ansible-clair
    image: dirane/jenkins
    ports:
      - '8001:80'
      - '50000:50000'
    privileged: true
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_home:/var/jenkins_home'
volumes:
  jenkins_home:
    driver: local
